stages:
    - test

run_tests:
    stage: test
    image: docker:24.0.5
    services:
      - name: docker:24.0.5-dind
        alias: docker
    variables:
      DOCKER_HOST: "tcp://docker:2375"
      DOCKER_TLS_CERTDIR: ""

    script:
        - docker compose --env-file=test.env -f=docker-compose-test.yml up --build --abort-on-container-exit
