version: "3.9"

name: "instagram-clone-test"
services:
  app:
    build:
      context: .
      target: "test"
    env_file:
        - test.env
    depends_on:
        database:
          condition: service_healthy
  database:
    image: postgres:15
    env_file:
      - test.env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 2s
      timeout: 5s
      retries: 5