version: "3.9"

name: "instagram-clone"
services:
  app:
    build: .
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
        - .:/home/app/code
    ports:
        - "127.0.0.1:8000:8000"
    env_file:
        - .env
    depends_on:
        database:
          condition: service_healthy
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 2s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
